version: '3.8'

services:
  # DSA Ladder Server Service
  server:
    image: dsa-ladder:latest # Replace with your actual DSA ladder image
    ports:
      - "3000:3000" # Expose the server on port 3000
    env_file:
      - .env
    deploy:
      replicas: 4 # 4 replicas for the DSA Ladder server


